### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by whqet** [praveenpuglia/github_markdown_snippets#3] opened 2016-03-12 06:05 UTC
> Type a tag name and hit tab.

not work.

type h2 and hit tab, then `<h2></h2>`
How to solve it?

**Comment by praveenpuglia** [comment] 2016-03-16 05:44
Looks like you have some other plugin overriding the tab trigger. Can you paste a list of plugins you have?

**Comment by praveenpuglia** [comment] 2016-04-15 05:48
@whqet - Is this resolved? I am closing this. if the issue persists, please reopen.

**Closed as completed by praveenpuglia** 2016-04-15 05:48 UTC

**Comment by cancastilho** [comment] 2016-11-16 22:27
Same problem here. I solved disabling Emmet plugin via package manager: CTRL+SHIFT+P > Package Control: Disable Package > Emmet.

**Comment by praveenpuglia** [comment] 2016-11-18 07:02
I use emmet along with this plugin and didn't face this problem. This is weird. I am guessing it's because of some sort of precedence in file type scopes. I'll have to check again.

**Comment by praveenpuglia** [comment] 2016-11-20 06:01
@cancastilho , @whqet - I can confirm that this doesn't work as expected when used alongside emmet. [Here's why](https://github.com/sergeche/emmet-sublime#tab-key-handler)

To get around the problem, go to **Preferences > Package Settings > Emmet > User Settings** and add the following in your settings file.

```
{
    "disable_tab_abbreviations_for_scopes": "text.html.markdown"
}
```

This should let markdown snippets take precedence over emmet's tab to expand abbreviations feature and provide correct snippets.

Hope this helps.

**Comment by cancastilho** [comment] 2016-11-20 14:19
That solved the problem. Thank you.
