### ISSUE TITLE
minor conflicts

### ISSUE THREAD

**Issue by ghost** [praveenpuglia/github_markdown_snippets#4] opened 2016-11-13 09:29 UTC
Nice work. Is it project still maintained?

I've run into a few problems, working in a .md file.

p triggers the html tag
shortcut after a shortcut won't trigger anything. Say I type h3, I get a header 3. Then I type li + tab and cursor jumps into a new line.

I don't have a clue as to why this happens. Sorry I can't be more helpful.

**Comment by praveenpuglia** [comment] 2016-11-13 14:42
Hi! Thanks for coming up here and letting me know. I have not expanded the project because I didn't find what else to expand to. If you have ideas, feel free to contribute :)

About the issue.

`p` is not a valid tab trigger for this package. Since a new line creates a paragraph in markdown, I didn't want to create another tab trigger just to do that. So 

```
p => [TAB] = <p></p>
```

... is expected.

Same goes for `li`. 

Here's a list of all tab triggers and what they result into.

http://praveenpuglia.com/github_markdown_snippets/

Note - If the tab trigger doesn't work as expected, try hitting the _escape_ key to get out of the snippet context and try again.

Let me know if the above steps solve the issues. :)

**Comment by ghost** [comment] 2016-11-13 20:44
Oh no! That p-thing was stupid of me. I was just trying the snippets out and forgot about it. Sorry.
Scape works, but it is still one click too much. I'll keep trying and see how it goes.

Good work.

**Comment by praveenpuglia** [comment] 2016-11-14 04:48
I think that's how tab triggers and snippets in sublime works. When a snippet inserts a template, the tab get's into the snippet context and cycles through the cursor placements/markers so you can type easily. When a defined exit marker in a snippet is found, the tab key comes out of that context and works normally.

If you did not want that to work like that, you can hit escape and the tab key goes back to normal. Guess it's an expected behaviour. So closing this one.

Feel free to open if the issue persists.

Thanks :)

**Closed as completed by praveenpuglia** 2016-11-14 04:48 UTC

**Comment by praveenpuglia** [comment] 2016-11-20 06:02
@mugaidavid - have a look at this one. 
https://github.com/praveenpuglia/github_markdown_snippets/issues/3#issuecomment-261760987
